SELECT 'CMOPTIONS' AS OPT_TABLE, D.OPT_GRP_ID, D.OPT_NUM_ID, D.OPT_NAME, D.OPT_BYTE, D.OPT_TEXT, D.OPT_NUMB, D.OPT_VALTYP, D.OPT_MOD, D.OPT_TAB, D.OPT_ID, D.OPT_VALID_TYP, D.OPT_VALID_VAL, D.OPT_HIDDEN, D.OPT_UI_GRP, D.OPT_ORDER FROM LUCITYDEV..CMOPTIONS D LEFT JOIN LUCITYNIGHTLY..CMOPTIONS N ON D.OPT_ID = N.OPT_ID WHERE N.OPT_ID IS NULL
UNION
SELECT 'PKOPTIONS' AS OPT_TABLE, D.OPT_GRP_ID, D.OPT_NUM_ID, D.OPT_NAME, D.OPT_BYTE, D.OPT_TEXT, D.OPT_NUMB, D.OPT_VALTYP, D.OPT_MOD, D.OPT_TAB, D.OPT_ID, D.OPT_VALID_TYP, D.OPT_VALID_VAL, D.OPT_HIDDEN, D.OPT_UI_GRP, D.OPT_ORDER FROM LUCITYDEV..PKOPTIONS D LEFT JOIN LUCITYNIGHTLY..PKOPTIONS N ON D.OPT_ID = N.OPT_ID WHERE N.OPT_ID IS NULL
UNION
SELECT 'SWOPTIONS' AS OPT_TABLE, D.OPT_GRP_ID, D.OPT_NUM_ID, D.OPT_NAME, D.OPT_BYTE, D.OPT_TEXT, D.OPT_NUMB, D.OPT_VALTYP, D.OPT_MOD, D.OPT_TAB, D.OPT_ID, D.OPT_VALID_TYP, D.OPT_VALID_VAL, D.OPT_HIDDEN, D.OPT_UI_GRP, D.OPT_ORDER FROM LUCITYDEV..SWOPTIONS D LEFT JOIN LUCITYNIGHTLY..SWOPTIONS N ON D.OPT_ID = N.OPT_ID WHERE N.OPT_ID IS NULL
UNION
SELECT 'SMOPTIONS' AS OPT_TABLE, D.OPT_GRP_ID, D.OPT_NUM_ID, D.OPT_NAME, D.OPT_BYTE, D.OPT_TEXT, D.OPT_NUMB, D.OPT_VALTYP, D.OPT_MOD, D.OPT_TAB, D.OPT_ID, D.OPT_VALID_TYP, D.OPT_VALID_VAL, D.OPT_HIDDEN, D.OPT_UI_GRP, D.OPT_ORDER FROM LUCITYDEV..SMOPTIONS D LEFT JOIN LUCITYNIGHTLY..SMOPTIONS N ON D.OPT_ID = N.OPT_ID WHERE N.OPT_ID IS NULL
UNION
SELECT 'STOPTIONS' AS OPT_TABLE, D.OPT_GRP_ID, D.OPT_NUM_ID, D.OPT_NAME, D.OPT_BYTE, D.OPT_TEXT, D.OPT_NUMB, D.OPT_VALTYP, D.OPT_MOD, D.OPT_TAB, D.OPT_ID, D.OPT_VALID_TYP, D.OPT_VALID_VAL, D.OPT_HIDDEN, D.OPT_UI_GRP, D.OPT_ORDER FROM LUCITYDEV..STOPTIONS D LEFT JOIN LUCITYNIGHTLY..STOPTIONS N ON D.OPT_ID = N.OPT_ID WHERE N.OPT_ID IS NULL
UNION
SELECT 'WTOPTIONS' AS OPT_TABLE, D.OPT_GRP_ID, D.OPT_NUM_ID, D.OPT_NAME, D.OPT_BYTE, D.OPT_TEXT, D.OPT_NUMB, D.OPT_VALTYP, D.OPT_MOD, D.OPT_TAB, D.OPT_ID, D.OPT_VALID_TYP, D.OPT_VALID_VAL, D.OPT_HIDDEN, D.OPT_UI_GRP, D.OPT_ORDER FROM LUCITYDEV..WTOPTIONS D LEFT JOIN LUCITYNIGHTLY..WTOPTIONS N ON D.OPT_ID = N.OPT_ID WHERE N.OPT_ID IS NULL
UNION
SELECT 'WKOPTIONS' AS OPT_TABLE, D.OPT_GRP_ID, D.OPT_NUM_ID, D.OPT_NAME, D.OPT_BYTE, D.OPT_TEXT, D.OPT_NUMB, D.OPT_VALTYP, D.OPT_MOD, D.OPT_TAB, D.OPT_ID, D.OPT_VALID_TYP, D.OPT_VALID_VAL, D.OPT_HIDDEN, D.OPT_UI_GRP, D.OPT_ORDER FROM LUCITYDEV..WKOPTIONS D LEFT JOIN LUCITYNIGHTLY..WKOPTIONS N ON D.OPT_ID = N.OPT_ID WHERE N.OPT_ID IS NULL


SELECT D.SYSSET_ID, D.SYSSET_NAME, D.SYSSET_VALUE, D.SYSSET_CATEGORY, D.SYSSET_LABEL FROM LUCITYDEV..SYSTEMSETTINGS D LEFT JOIN LucityNightly..SYSTEMSETTINGS N ON D.SYSSET_ID = N.SYSSET_ID WHERE N.SYSSET_ID IS NULL