DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM pg_roles WHERE rolname = 'lucitygateway') THEN
	CREATE ROLE lucitygateway WITH
		NOLOGIN
		NOSUPERUSER
		INHERIT
		NOCREATEDB
		NOCREATEROLE
		NOREPLICATION;
END IF;
END$$;

DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM pg_roles WHERE rolname = 'lucityreaderwriter') THEN  
	CREATE ROLE lucityreaderwriter WITH
		NOLOGIN
		NOSUPERUSER
		INHERIT
		NOCREATEDB
		NOCREATEROLE
		NOREPLICATION;
END IF;
END$$;