CREATE TRIGGER [TRIGINTERNAL_CHECK_LENGTH_OF_SP_NAME] 
ON DATABASE 
FOR create_procedure 
AS
DECLARE @data XML, @msg VARCHAR(1000), @name VARCHAR(100)
SET @data = EVENTDATA()

SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON

SET @msg = ''
SET @name = @data.value('(/EVENT_INSTANCE/ObjectName)[1]', 'varchar(100)')

IF @name like 'SPGBA%' AND DATALENGTH(@name) > 32
		BEGIN
			SET @msg = 'Stored procedure name is too long.'
			RAISERROR (@msg , 16, 1)
			ROLLBACK TRANSACTION
		END
GO