IF (SUSER_ID('GBAMS\LucitySQLServerAdmins') IS NULL) BEGIN CREATE LOGIN [GBAMS\LucitySQLServerAdmins] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;
IF (SUSER_ID('GBAMS\gbaMSDEVInstanceUsers') IS NULL) BEGIN CREATE LOGIN [GBAMS\gbaMSDEVInstanceUsers] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;
IF (SUSER_ID('GBAMS\gbaMSDevDBOwners') IS NULL) BEGIN CREATE LOGIN [GBAMS\gbaMSDevDBOwners] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;
IF (SUSER_ID('LUCITY_GATEWAY') IS NULL) BEGIN CREATE LOGIN [LUCITY_GATEWAY] WITH PASSWORD = 0x0100F78547FF4504E77149D00EA816E2CD293D1021595F965E27 HASHED, CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF, DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;
IF (SUSER_ID('LUCITY_USER') IS NULL) BEGIN CREATE LOGIN [LUCITY_USER] WITH PASSWORD = 0x0100C0962831E1C8CB776DAC0B1C56594B772BC603BCF9F96E52 HASHED, CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF, DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;
IF (SUSER_ID('LinkedServerLogin') IS NULL) BEGIN CREATE LOGIN [LinkedServerLogin] WITH PASSWORD = 0x0100BB5029DC907E4F834B8D17D1D58CB19F698D6A18814BFB29 HASHED, CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF, DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;
IF (SUSER_ID('BobTheBuilder') IS NULL) BEGIN CREATE LOGIN [BobTheBuilder] WITH PASSWORD = 0x01008D33D08B99B1F3801D4E11F08364411AD8ABEE0DAFA9A3A9 HASHED, CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF, DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;
IF (SUSER_ID('GBAMS\LucityDevDBHostAdmins') IS NULL) BEGIN CREATE LOGIN [GBAMS\LucityDevDBHostAdmins] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;
IF (SUSER_ID('LucityDevOps') IS NULL) BEGIN CREATE LOGIN [LucityDevOps] WITH PASSWORD = 0x0100FE4DD26AF80FE3B5D2DF79A8A51D6B09E7168A9828CE1DE1 HASHED, CHECK_EXPIRATION = OFF, CHECK_POLICY = ON, DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english] END;

EXEC master..sp_addsrvrolemember @loginame = N'GBAMS\LucitySQLServerAdmins', @rolename = N'sysadmin'  
EXEC master..sp_addsrvrolemember @loginame = N'GBAMS\LucityDevDBHostAdmins', @rolename = N'sysadmin'  

GRANT CONNECT SQL TO [GBAMS\LucitySQLServerAdmins]
GRANT ALTER TRACE TO [GBAMS\gbaMSDEVInstanceUsers]
GRANT CONNECT SQL TO [GBAMS\gbaMSDEVInstanceUsers]
GRANT VIEW SERVER STATE TO [GBAMS\gbaMSDEVInstanceUsers]
GRANT CONNECT SQL TO [GBAMS\gbaMSDevDBOwners]
GRANT CONNECT SQL TO [LUCITY_GATEWAY]
GRANT CONNECT SQL TO [LUCITY_USER]
GRANT VIEW ANY DEFINITION TO [LUCITY_USER]
GRANT VIEW SERVER STATE TO [LUCITY_USER]
GRANT CONNECT SQL TO [LinkedServerLogin]
GRANT CONNECT SQL TO [BobTheBuilder]
GRANT CONNECT SQL TO [GBAMS\LucityDevDBHostAdmins]
GRANT CONNECT SQL TO [LucityDevOps]